# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ckerneldata', [dirname(__file__)])
        except ImportError:
            import _ckerneldata
            return _ckerneldata
        if fp is not None:
            try:
                _mod = imp.load_module('_ckerneldata', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ckerneldata = swig_import_helper()
    del swig_import_helper
else:
    import _ckerneldata
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ckerneldata.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _ckerneldata.SwigPyIterator_value(self)
    def incr(self, n = 1): return _ckerneldata.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _ckerneldata.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _ckerneldata.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _ckerneldata.SwigPyIterator_equal(self, *args)
    def copy(self): return _ckerneldata.SwigPyIterator_copy(self)
    def next(self): return _ckerneldata.SwigPyIterator_next(self)
    def __next__(self): return _ckerneldata.SwigPyIterator___next__(self)
    def previous(self): return _ckerneldata.SwigPyIterator_previous(self)
    def advance(self, *args): return _ckerneldata.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _ckerneldata.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _ckerneldata.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _ckerneldata.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _ckerneldata.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _ckerneldata.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _ckerneldata.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _ckerneldata.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ckerneldata.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ckerneldata.IntVector___nonzero__(self)
    def __bool__(self): return _ckerneldata.IntVector___bool__(self)
    def __len__(self): return _ckerneldata.IntVector___len__(self)
    def pop(self): return _ckerneldata.IntVector_pop(self)
    def __getslice__(self, *args): return _ckerneldata.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ckerneldata.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ckerneldata.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ckerneldata.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ckerneldata.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ckerneldata.IntVector___setitem__(self, *args)
    def append(self, *args): return _ckerneldata.IntVector_append(self, *args)
    def empty(self): return _ckerneldata.IntVector_empty(self)
    def size(self): return _ckerneldata.IntVector_size(self)
    def clear(self): return _ckerneldata.IntVector_clear(self)
    def swap(self, *args): return _ckerneldata.IntVector_swap(self, *args)
    def get_allocator(self): return _ckerneldata.IntVector_get_allocator(self)
    def begin(self): return _ckerneldata.IntVector_begin(self)
    def end(self): return _ckerneldata.IntVector_end(self)
    def rbegin(self): return _ckerneldata.IntVector_rbegin(self)
    def rend(self): return _ckerneldata.IntVector_rend(self)
    def pop_back(self): return _ckerneldata.IntVector_pop_back(self)
    def erase(self, *args): return _ckerneldata.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ckerneldata.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ckerneldata.IntVector_push_back(self, *args)
    def front(self): return _ckerneldata.IntVector_front(self)
    def back(self): return _ckerneldata.IntVector_back(self)
    def assign(self, *args): return _ckerneldata.IntVector_assign(self, *args)
    def resize(self, *args): return _ckerneldata.IntVector_resize(self, *args)
    def insert(self, *args): return _ckerneldata.IntVector_insert(self, *args)
    def reserve(self, *args): return _ckerneldata.IntVector_reserve(self, *args)
    def capacity(self): return _ckerneldata.IntVector_capacity(self)
    __swig_destroy__ = _ckerneldata.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _ckerneldata.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ckerneldata.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ckerneldata.DoubleVector___nonzero__(self)
    def __bool__(self): return _ckerneldata.DoubleVector___bool__(self)
    def __len__(self): return _ckerneldata.DoubleVector___len__(self)
    def pop(self): return _ckerneldata.DoubleVector_pop(self)
    def __getslice__(self, *args): return _ckerneldata.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ckerneldata.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ckerneldata.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ckerneldata.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ckerneldata.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ckerneldata.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _ckerneldata.DoubleVector_append(self, *args)
    def empty(self): return _ckerneldata.DoubleVector_empty(self)
    def size(self): return _ckerneldata.DoubleVector_size(self)
    def clear(self): return _ckerneldata.DoubleVector_clear(self)
    def swap(self, *args): return _ckerneldata.DoubleVector_swap(self, *args)
    def get_allocator(self): return _ckerneldata.DoubleVector_get_allocator(self)
    def begin(self): return _ckerneldata.DoubleVector_begin(self)
    def end(self): return _ckerneldata.DoubleVector_end(self)
    def rbegin(self): return _ckerneldata.DoubleVector_rbegin(self)
    def rend(self): return _ckerneldata.DoubleVector_rend(self)
    def pop_back(self): return _ckerneldata.DoubleVector_pop_back(self)
    def erase(self, *args): return _ckerneldata.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ckerneldata.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ckerneldata.DoubleVector_push_back(self, *args)
    def front(self): return _ckerneldata.DoubleVector_front(self)
    def back(self): return _ckerneldata.DoubleVector_back(self)
    def assign(self, *args): return _ckerneldata.DoubleVector_assign(self, *args)
    def resize(self, *args): return _ckerneldata.DoubleVector_resize(self, *args)
    def insert(self, *args): return _ckerneldata.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _ckerneldata.DoubleVector_reserve(self, *args)
    def capacity(self): return _ckerneldata.DoubleVector_capacity(self)
    __swig_destroy__ = _ckerneldata.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _ckerneldata.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ckerneldata.FloatVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ckerneldata.FloatVector___nonzero__(self)
    def __bool__(self): return _ckerneldata.FloatVector___bool__(self)
    def __len__(self): return _ckerneldata.FloatVector___len__(self)
    def pop(self): return _ckerneldata.FloatVector_pop(self)
    def __getslice__(self, *args): return _ckerneldata.FloatVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ckerneldata.FloatVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ckerneldata.FloatVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ckerneldata.FloatVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ckerneldata.FloatVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ckerneldata.FloatVector___setitem__(self, *args)
    def append(self, *args): return _ckerneldata.FloatVector_append(self, *args)
    def empty(self): return _ckerneldata.FloatVector_empty(self)
    def size(self): return _ckerneldata.FloatVector_size(self)
    def clear(self): return _ckerneldata.FloatVector_clear(self)
    def swap(self, *args): return _ckerneldata.FloatVector_swap(self, *args)
    def get_allocator(self): return _ckerneldata.FloatVector_get_allocator(self)
    def begin(self): return _ckerneldata.FloatVector_begin(self)
    def end(self): return _ckerneldata.FloatVector_end(self)
    def rbegin(self): return _ckerneldata.FloatVector_rbegin(self)
    def rend(self): return _ckerneldata.FloatVector_rend(self)
    def pop_back(self): return _ckerneldata.FloatVector_pop_back(self)
    def erase(self, *args): return _ckerneldata.FloatVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ckerneldata.new_FloatVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ckerneldata.FloatVector_push_back(self, *args)
    def front(self): return _ckerneldata.FloatVector_front(self)
    def back(self): return _ckerneldata.FloatVector_back(self)
    def assign(self, *args): return _ckerneldata.FloatVector_assign(self, *args)
    def resize(self, *args): return _ckerneldata.FloatVector_resize(self, *args)
    def insert(self, *args): return _ckerneldata.FloatVector_insert(self, *args)
    def reserve(self, *args): return _ckerneldata.FloatVector_reserve(self, *args)
    def capacity(self): return _ckerneldata.FloatVector_capacity(self)
    __swig_destroy__ = _ckerneldata.delete_FloatVector
    __del__ = lambda self : None;
FloatVector_swigregister = _ckerneldata.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

class DataSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DataSet, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def size(self): return _ckerneldata.DataSet_size(self)
    __swig_setmethods__["Y"] = _ckerneldata.DataSet_Y_set
    __swig_getmethods__["Y"] = _ckerneldata.DataSet_Y_get
    if _newclass:Y = _swig_property(_ckerneldata.DataSet_Y_get, _ckerneldata.DataSet_Y_set)
    __swig_setmethods__["norms"] = _ckerneldata.DataSet_norms_set
    __swig_getmethods__["norms"] = _ckerneldata.DataSet_norms_get
    if _newclass:norms = _swig_property(_ckerneldata.DataSet_norms_get, _ckerneldata.DataSet_norms_set)
    def setY(self, *args): return _ckerneldata.DataSet_setY(self, *args)
    def computeNorms(self): return _ckerneldata.DataSet_computeNorms(self)
    __swig_setmethods__["kernel"] = _ckerneldata.DataSet_kernel_set
    __swig_getmethods__["kernel"] = _ckerneldata.DataSet_kernel_get
    if _newclass:kernel = _swig_property(_ckerneldata.DataSet_kernel_get, _ckerneldata.DataSet_kernel_set)
    def setKernel(self, *args): return _ckerneldata.DataSet_setKernel(self, *args)
    def attachKernel(self, *args): return _ckerneldata.DataSet_attachKernel(self, *args)
    def getKernelMatrixAsVector(self): return _ckerneldata.DataSet_getKernelMatrixAsVector(self)
    def dotProduct(self, *args): return _ckerneldata.DataSet_dotProduct(self, *args)
    def duplicate(self, *args): return _ckerneldata.DataSet_duplicate(self, *args)
    def castToBase(self): return _ckerneldata.DataSet_castToBase(self)
    def show(self): return _ckerneldata.DataSet_show(self)
    __swig_destroy__ = _ckerneldata.delete_DataSet
    __del__ = lambda self : None;
DataSet_swigregister = _ckerneldata.DataSet_swigregister
DataSet_swigregister(DataSet)

class KernelData(DataSet):
    __swig_setmethods__ = {}
    for _s in [DataSet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, KernelData, name, value)
    __swig_getmethods__ = {}
    for _s in [DataSet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, KernelData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["kernelMatrix"] = _ckerneldata.KernelData_kernelMatrix_set
    __swig_getmethods__["kernelMatrix"] = _ckerneldata.KernelData_kernelMatrix_get
    if _newclass:kernelMatrix = _swig_property(_ckerneldata.KernelData_kernelMatrix_get, _ckerneldata.KernelData_kernelMatrix_set)
    __swig_setmethods__["patternPtr"] = _ckerneldata.KernelData_patternPtr_set
    __swig_getmethods__["patternPtr"] = _ckerneldata.KernelData_patternPtr_get
    if _newclass:patternPtr = _swig_property(_ckerneldata.KernelData_patternPtr_get, _ckerneldata.KernelData_patternPtr_set)
    def size(self): return _ckerneldata.KernelData_size(self)
    def dotProduct(self, *args): return _ckerneldata.KernelData_dotProduct(self, *args)
    def center(self): return _ckerneldata.KernelData_center(self)
    def show(self): return _ckerneldata.KernelData_show(self)
    def addRow(self, *args): return _ckerneldata.KernelData_addRow(self, *args)
    def castToBase(self): return _ckerneldata.KernelData_castToBase(self)
    def duplicate(self, *args): return _ckerneldata.KernelData_duplicate(self, *args)
    def __init__(self, *args): 
        this = _ckerneldata.new_KernelData(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ckerneldata.delete_KernelData
    __del__ = lambda self : None;
KernelData_swigregister = _ckerneldata.KernelData_swigregister
KernelData_swigregister(KernelData)



