# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ckernel', [dirname(__file__)])
        except ImportError:
            import _ckernel
            return _ckernel
        if fp is not None:
            try:
                _mod = imp.load_module('_ckernel', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ckernel = swig_import_helper()
    del swig_import_helper
else:
    import _ckernel
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ckernel.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _ckernel.SwigPyIterator_value(self)
    def incr(self, n = 1): return _ckernel.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _ckernel.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _ckernel.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _ckernel.SwigPyIterator_equal(self, *args)
    def copy(self): return _ckernel.SwigPyIterator_copy(self)
    def next(self): return _ckernel.SwigPyIterator_next(self)
    def __next__(self): return _ckernel.SwigPyIterator___next__(self)
    def previous(self): return _ckernel.SwigPyIterator_previous(self)
    def advance(self, *args): return _ckernel.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _ckernel.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _ckernel.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _ckernel.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _ckernel.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _ckernel.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _ckernel.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _ckernel.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ckernel.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ckernel.IntVector___nonzero__(self)
    def __bool__(self): return _ckernel.IntVector___bool__(self)
    def __len__(self): return _ckernel.IntVector___len__(self)
    def pop(self): return _ckernel.IntVector_pop(self)
    def __getslice__(self, *args): return _ckernel.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ckernel.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ckernel.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ckernel.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ckernel.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ckernel.IntVector___setitem__(self, *args)
    def append(self, *args): return _ckernel.IntVector_append(self, *args)
    def empty(self): return _ckernel.IntVector_empty(self)
    def size(self): return _ckernel.IntVector_size(self)
    def clear(self): return _ckernel.IntVector_clear(self)
    def swap(self, *args): return _ckernel.IntVector_swap(self, *args)
    def get_allocator(self): return _ckernel.IntVector_get_allocator(self)
    def begin(self): return _ckernel.IntVector_begin(self)
    def end(self): return _ckernel.IntVector_end(self)
    def rbegin(self): return _ckernel.IntVector_rbegin(self)
    def rend(self): return _ckernel.IntVector_rend(self)
    def pop_back(self): return _ckernel.IntVector_pop_back(self)
    def erase(self, *args): return _ckernel.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ckernel.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ckernel.IntVector_push_back(self, *args)
    def front(self): return _ckernel.IntVector_front(self)
    def back(self): return _ckernel.IntVector_back(self)
    def assign(self, *args): return _ckernel.IntVector_assign(self, *args)
    def resize(self, *args): return _ckernel.IntVector_resize(self, *args)
    def insert(self, *args): return _ckernel.IntVector_insert(self, *args)
    def reserve(self, *args): return _ckernel.IntVector_reserve(self, *args)
    def capacity(self): return _ckernel.IntVector_capacity(self)
    __swig_destroy__ = _ckernel.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _ckernel.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ckernel.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ckernel.DoubleVector___nonzero__(self)
    def __bool__(self): return _ckernel.DoubleVector___bool__(self)
    def __len__(self): return _ckernel.DoubleVector___len__(self)
    def pop(self): return _ckernel.DoubleVector_pop(self)
    def __getslice__(self, *args): return _ckernel.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ckernel.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ckernel.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ckernel.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ckernel.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ckernel.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _ckernel.DoubleVector_append(self, *args)
    def empty(self): return _ckernel.DoubleVector_empty(self)
    def size(self): return _ckernel.DoubleVector_size(self)
    def clear(self): return _ckernel.DoubleVector_clear(self)
    def swap(self, *args): return _ckernel.DoubleVector_swap(self, *args)
    def get_allocator(self): return _ckernel.DoubleVector_get_allocator(self)
    def begin(self): return _ckernel.DoubleVector_begin(self)
    def end(self): return _ckernel.DoubleVector_end(self)
    def rbegin(self): return _ckernel.DoubleVector_rbegin(self)
    def rend(self): return _ckernel.DoubleVector_rend(self)
    def pop_back(self): return _ckernel.DoubleVector_pop_back(self)
    def erase(self, *args): return _ckernel.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ckernel.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ckernel.DoubleVector_push_back(self, *args)
    def front(self): return _ckernel.DoubleVector_front(self)
    def back(self): return _ckernel.DoubleVector_back(self)
    def assign(self, *args): return _ckernel.DoubleVector_assign(self, *args)
    def resize(self, *args): return _ckernel.DoubleVector_resize(self, *args)
    def insert(self, *args): return _ckernel.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _ckernel.DoubleVector_reserve(self, *args)
    def capacity(self): return _ckernel.DoubleVector_capacity(self)
    __swig_destroy__ = _ckernel.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _ckernel.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ckernel.FloatVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ckernel.FloatVector___nonzero__(self)
    def __bool__(self): return _ckernel.FloatVector___bool__(self)
    def __len__(self): return _ckernel.FloatVector___len__(self)
    def pop(self): return _ckernel.FloatVector_pop(self)
    def __getslice__(self, *args): return _ckernel.FloatVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ckernel.FloatVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ckernel.FloatVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ckernel.FloatVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ckernel.FloatVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ckernel.FloatVector___setitem__(self, *args)
    def append(self, *args): return _ckernel.FloatVector_append(self, *args)
    def empty(self): return _ckernel.FloatVector_empty(self)
    def size(self): return _ckernel.FloatVector_size(self)
    def clear(self): return _ckernel.FloatVector_clear(self)
    def swap(self, *args): return _ckernel.FloatVector_swap(self, *args)
    def get_allocator(self): return _ckernel.FloatVector_get_allocator(self)
    def begin(self): return _ckernel.FloatVector_begin(self)
    def end(self): return _ckernel.FloatVector_end(self)
    def rbegin(self): return _ckernel.FloatVector_rbegin(self)
    def rend(self): return _ckernel.FloatVector_rend(self)
    def pop_back(self): return _ckernel.FloatVector_pop_back(self)
    def erase(self, *args): return _ckernel.FloatVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ckernel.new_FloatVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ckernel.FloatVector_push_back(self, *args)
    def front(self): return _ckernel.FloatVector_front(self)
    def back(self): return _ckernel.FloatVector_back(self)
    def assign(self, *args): return _ckernel.FloatVector_assign(self, *args)
    def resize(self, *args): return _ckernel.FloatVector_resize(self, *args)
    def insert(self, *args): return _ckernel.FloatVector_insert(self, *args)
    def reserve(self, *args): return _ckernel.FloatVector_reserve(self, *args)
    def capacity(self): return _ckernel.FloatVector_capacity(self)
    __swig_destroy__ = _ckernel.delete_FloatVector
    __del__ = lambda self : None;
FloatVector_swigregister = _ckernel.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

NONE = _ckernel.NONE
COSINE = _ckernel.COSINE
TANIMOTO = _ckernel.TANIMOTO
DICES = _ckernel.DICES
class Kernel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Kernel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Kernel, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ckernel.delete_Kernel
    __del__ = lambda self : None;
    def duplicate(self): return _ckernel.Kernel_duplicate(self)
    def castToBase(self): return _ckernel.Kernel_castToBase(self)
    def eval(self, *args): return _ckernel.Kernel_eval(self, *args)
    __swig_setmethods__["normalization"] = _ckernel.Kernel_normalization_set
    __swig_getmethods__["normalization"] = _ckernel.Kernel_normalization_get
    if _newclass:normalization = _swig_property(_ckernel.Kernel_normalization_get, _ckernel.Kernel_normalization_set)
    def normalize(self, *args): return _ckernel.Kernel_normalize(self, *args)
Kernel_swigregister = _ckernel.Kernel_swigregister
Kernel_swigregister(Kernel)

class Linear(Kernel):
    __swig_setmethods__ = {}
    for _s in [Kernel]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Linear, name, value)
    __swig_getmethods__ = {}
    for _s in [Kernel]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Linear, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _ckernel.new_Linear(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ckernel.delete_Linear
    __del__ = lambda self : None;
    def duplicate(self): return _ckernel.Linear_duplicate(self)
    def castToBase(self): return _ckernel.Linear_castToBase(self)
    def eval(self, *args): return _ckernel.Linear_eval(self, *args)
Linear_swigregister = _ckernel.Linear_swigregister
Linear_swigregister(Linear)

class Cosine(Kernel):
    __swig_setmethods__ = {}
    for _s in [Kernel]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cosine, name, value)
    __swig_getmethods__ = {}
    for _s in [Kernel]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Cosine, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _ckernel.new_Cosine(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ckernel.delete_Cosine
    __del__ = lambda self : None;
    def duplicate(self): return _ckernel.Cosine_duplicate(self)
    def castToBase(self): return _ckernel.Cosine_castToBase(self)
    def eval(self, *args): return _ckernel.Cosine_eval(self, *args)
Cosine_swigregister = _ckernel.Cosine_swigregister
Cosine_swigregister(Cosine)

class Polynomial(Kernel):
    __swig_setmethods__ = {}
    for _s in [Kernel]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Polynomial, name, value)
    __swig_getmethods__ = {}
    for _s in [Kernel]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Polynomial, name)
    __repr__ = _swig_repr
    __swig_setmethods__["degree"] = _ckernel.Polynomial_degree_set
    __swig_getmethods__["degree"] = _ckernel.Polynomial_degree_get
    if _newclass:degree = _swig_property(_ckernel.Polynomial_degree_get, _ckernel.Polynomial_degree_set)
    __swig_setmethods__["additiveConst"] = _ckernel.Polynomial_additiveConst_set
    __swig_getmethods__["additiveConst"] = _ckernel.Polynomial_additiveConst_get
    if _newclass:additiveConst = _swig_property(_ckernel.Polynomial_additiveConst_get, _ckernel.Polynomial_additiveConst_set)
    def __init__(self, *args): 
        this = _ckernel.new_Polynomial(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ckernel.delete_Polynomial
    __del__ = lambda self : None;
    def duplicate(self): return _ckernel.Polynomial_duplicate(self)
    def castToBase(self): return _ckernel.Polynomial_castToBase(self)
    def eval(self, *args): return _ckernel.Polynomial_eval(self, *args)
    def setDegree(self, *args): return _ckernel.Polynomial_setDegree(self, *args)
    def setAdditiveConst(self, *args): return _ckernel.Polynomial_setAdditiveConst(self, *args)
Polynomial_swigregister = _ckernel.Polynomial_swigregister
Polynomial_swigregister(Polynomial)

class Gaussian(Kernel):
    __swig_setmethods__ = {}
    for _s in [Kernel]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Gaussian, name, value)
    __swig_getmethods__ = {}
    for _s in [Kernel]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Gaussian, name)
    __repr__ = _swig_repr
    __swig_setmethods__["gamma"] = _ckernel.Gaussian_gamma_set
    __swig_getmethods__["gamma"] = _ckernel.Gaussian_gamma_get
    if _newclass:gamma = _swig_property(_ckernel.Gaussian_gamma_get, _ckernel.Gaussian_gamma_set)
    def __init__(self, *args): 
        this = _ckernel.new_Gaussian(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ckernel.delete_Gaussian
    __del__ = lambda self : None;
    def duplicate(self): return _ckernel.Gaussian_duplicate(self)
    def castToBase(self): return _ckernel.Gaussian_castToBase(self)
    def eval(self, *args): return _ckernel.Gaussian_eval(self, *args)
    def setGamma(self, *args): return _ckernel.Gaussian_setGamma(self, *args)
Gaussian_swigregister = _ckernel.Gaussian_swigregister
Gaussian_swigregister(Gaussian)

class KernelMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KernelMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KernelMatrix, name)
    __repr__ = _swig_repr
    __swig_setmethods__["matrix"] = _ckernel.KernelMatrix_matrix_set
    __swig_getmethods__["matrix"] = _ckernel.KernelMatrix_matrix_get
    if _newclass:matrix = _swig_property(_ckernel.KernelMatrix_matrix_get, _ckernel.KernelMatrix_matrix_set)
    __swig_setmethods__["refCount"] = _ckernel.KernelMatrix_refCount_set
    __swig_getmethods__["refCount"] = _ckernel.KernelMatrix_refCount_get
    if _newclass:refCount = _swig_property(_ckernel.KernelMatrix_refCount_get, _ckernel.KernelMatrix_refCount_set)
    def size(self): return _ckernel.KernelMatrix_size(self)
    def addRow(self, *args): return _ckernel.KernelMatrix_addRow(self, *args)
    def getEntry(self, *args): return _ckernel.KernelMatrix_getEntry(self, *args)
    def center(self): return _ckernel.KernelMatrix_center(self)
    def show(self): return _ckernel.KernelMatrix_show(self)
    def __init__(self): 
        this = _ckernel.new_KernelMatrix()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ckernel.delete_KernelMatrix
    __del__ = lambda self : None;
KernelMatrix_swigregister = _ckernel.KernelMatrix_swigregister
KernelMatrix_swigregister(KernelMatrix)


def kernel2file(*args):
  return _ckernel.kernel2file(*args)
kernel2file = _ckernel.kernel2file


