# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cpairdataset', [dirname(__file__)])
        except ImportError:
            import _cpairdataset
            return _cpairdataset
        if fp is not None:
            try:
                _mod = imp.load_module('_cpairdataset', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cpairdataset = swig_import_helper()
    del swig_import_helper
else:
    import _cpairdataset
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cpairdataset.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _cpairdataset.SwigPyIterator_value(self)
    def incr(self, n = 1): return _cpairdataset.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _cpairdataset.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _cpairdataset.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _cpairdataset.SwigPyIterator_equal(self, *args)
    def copy(self): return _cpairdataset.SwigPyIterator_copy(self)
    def next(self): return _cpairdataset.SwigPyIterator_next(self)
    def __next__(self): return _cpairdataset.SwigPyIterator___next__(self)
    def previous(self): return _cpairdataset.SwigPyIterator_previous(self)
    def advance(self, *args): return _cpairdataset.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _cpairdataset.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _cpairdataset.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _cpairdataset.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _cpairdataset.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _cpairdataset.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _cpairdataset.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _cpairdataset.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _cpairdataset.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _cpairdataset.IntVector___nonzero__(self)
    def __bool__(self): return _cpairdataset.IntVector___bool__(self)
    def __len__(self): return _cpairdataset.IntVector___len__(self)
    def pop(self): return _cpairdataset.IntVector_pop(self)
    def __getslice__(self, *args): return _cpairdataset.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _cpairdataset.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _cpairdataset.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _cpairdataset.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _cpairdataset.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _cpairdataset.IntVector___setitem__(self, *args)
    def append(self, *args): return _cpairdataset.IntVector_append(self, *args)
    def empty(self): return _cpairdataset.IntVector_empty(self)
    def size(self): return _cpairdataset.IntVector_size(self)
    def clear(self): return _cpairdataset.IntVector_clear(self)
    def swap(self, *args): return _cpairdataset.IntVector_swap(self, *args)
    def get_allocator(self): return _cpairdataset.IntVector_get_allocator(self)
    def begin(self): return _cpairdataset.IntVector_begin(self)
    def end(self): return _cpairdataset.IntVector_end(self)
    def rbegin(self): return _cpairdataset.IntVector_rbegin(self)
    def rend(self): return _cpairdataset.IntVector_rend(self)
    def pop_back(self): return _cpairdataset.IntVector_pop_back(self)
    def erase(self, *args): return _cpairdataset.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _cpairdataset.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _cpairdataset.IntVector_push_back(self, *args)
    def front(self): return _cpairdataset.IntVector_front(self)
    def back(self): return _cpairdataset.IntVector_back(self)
    def assign(self, *args): return _cpairdataset.IntVector_assign(self, *args)
    def resize(self, *args): return _cpairdataset.IntVector_resize(self, *args)
    def insert(self, *args): return _cpairdataset.IntVector_insert(self, *args)
    def reserve(self, *args): return _cpairdataset.IntVector_reserve(self, *args)
    def capacity(self): return _cpairdataset.IntVector_capacity(self)
    __swig_destroy__ = _cpairdataset.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _cpairdataset.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _cpairdataset.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _cpairdataset.DoubleVector___nonzero__(self)
    def __bool__(self): return _cpairdataset.DoubleVector___bool__(self)
    def __len__(self): return _cpairdataset.DoubleVector___len__(self)
    def pop(self): return _cpairdataset.DoubleVector_pop(self)
    def __getslice__(self, *args): return _cpairdataset.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _cpairdataset.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _cpairdataset.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _cpairdataset.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _cpairdataset.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _cpairdataset.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _cpairdataset.DoubleVector_append(self, *args)
    def empty(self): return _cpairdataset.DoubleVector_empty(self)
    def size(self): return _cpairdataset.DoubleVector_size(self)
    def clear(self): return _cpairdataset.DoubleVector_clear(self)
    def swap(self, *args): return _cpairdataset.DoubleVector_swap(self, *args)
    def get_allocator(self): return _cpairdataset.DoubleVector_get_allocator(self)
    def begin(self): return _cpairdataset.DoubleVector_begin(self)
    def end(self): return _cpairdataset.DoubleVector_end(self)
    def rbegin(self): return _cpairdataset.DoubleVector_rbegin(self)
    def rend(self): return _cpairdataset.DoubleVector_rend(self)
    def pop_back(self): return _cpairdataset.DoubleVector_pop_back(self)
    def erase(self, *args): return _cpairdataset.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _cpairdataset.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _cpairdataset.DoubleVector_push_back(self, *args)
    def front(self): return _cpairdataset.DoubleVector_front(self)
    def back(self): return _cpairdataset.DoubleVector_back(self)
    def assign(self, *args): return _cpairdataset.DoubleVector_assign(self, *args)
    def resize(self, *args): return _cpairdataset.DoubleVector_resize(self, *args)
    def insert(self, *args): return _cpairdataset.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _cpairdataset.DoubleVector_reserve(self, *args)
    def capacity(self): return _cpairdataset.DoubleVector_capacity(self)
    __swig_destroy__ = _cpairdataset.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _cpairdataset.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class DataSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DataSet, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["Y"] = _cpairdataset.DataSet_Y_set
    __swig_getmethods__["Y"] = _cpairdataset.DataSet_Y_get
    if _newclass:Y = _swig_property(_cpairdataset.DataSet_Y_get, _cpairdataset.DataSet_Y_set)
    __swig_setmethods__["norms"] = _cpairdataset.DataSet_norms_set
    __swig_getmethods__["norms"] = _cpairdataset.DataSet_norms_get
    if _newclass:norms = _swig_property(_cpairdataset.DataSet_norms_get, _cpairdataset.DataSet_norms_set)
    __swig_setmethods__["kernel"] = _cpairdataset.DataSet_kernel_set
    __swig_getmethods__["kernel"] = _cpairdataset.DataSet_kernel_get
    if _newclass:kernel = _swig_property(_cpairdataset.DataSet_kernel_get, _cpairdataset.DataSet_kernel_set)
    def setY(self, *args): return _cpairdataset.DataSet_setY(self, *args)
    def computeNorms(self): return _cpairdataset.DataSet_computeNorms(self)
    def setKernel(self, *args): return _cpairdataset.DataSet_setKernel(self, *args)
    def attachKernel(self, *args): return _cpairdataset.DataSet_attachKernel(self, *args)
    def getKernelMatrixAsVector(self): return _cpairdataset.DataSet_getKernelMatrixAsVector(self)
    def size(self): return _cpairdataset.DataSet_size(self)
    def dotProduct(self, *args): return _cpairdataset.DataSet_dotProduct(self, *args)
    def duplicate(self, *args): return _cpairdataset.DataSet_duplicate(self, *args)
    def castToBase(self): return _cpairdataset.DataSet_castToBase(self)
    def show(self): return _cpairdataset.DataSet_show(self)
    __swig_destroy__ = _cpairdataset.delete_DataSet
    __del__ = lambda self : None;
DataSet_swigregister = _cpairdataset.DataSet_swigregister
DataSet_swigregister(DataSet)

class PairDataSet(DataSet):
    __swig_setmethods__ = {}
    for _s in [DataSet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairDataSet, name, value)
    __swig_getmethods__ = {}
    for _s in [DataSet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PairDataSet, name)
    __repr__ = _swig_repr
    __swig_setmethods__["first"] = _cpairdataset.PairDataSet_first_set
    __swig_getmethods__["first"] = _cpairdataset.PairDataSet_first_get
    if _newclass:first = _swig_property(_cpairdataset.PairDataSet_first_get, _cpairdataset.PairDataSet_first_set)
    __swig_setmethods__["second"] = _cpairdataset.PairDataSet_second_set
    __swig_getmethods__["second"] = _cpairdataset.PairDataSet_second_get
    if _newclass:second = _swig_property(_cpairdataset.PairDataSet_second_get, _cpairdataset.PairDataSet_second_set)
    __swig_setmethods__["data"] = _cpairdataset.PairDataSet_data_set
    __swig_getmethods__["data"] = _cpairdataset.PairDataSet_data_get
    if _newclass:data = _swig_property(_cpairdataset.PairDataSet_data_get, _cpairdataset.PairDataSet_data_set)
    def size(self): return _cpairdataset.PairDataSet_size(self)
    def dotProduct(self, *args): return _cpairdataset.PairDataSet_dotProduct(self, *args)
    def show(self): return _cpairdataset.PairDataSet_show(self)
    def castToBase(self): return _cpairdataset.PairDataSet_castToBase(self)
    def duplicate(self, *args): return _cpairdataset.PairDataSet_duplicate(self, *args)
    def __init__(self, *args): 
        this = _cpairdataset.new_PairDataSet(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cpairdataset.delete_PairDataSet
    __del__ = lambda self : None;
PairDataSet_swigregister = _cpairdataset.PairDataSet_swigregister
PairDataSet_swigregister(PairDataSet)

class PairDataSetSum(PairDataSet):
    __swig_setmethods__ = {}
    for _s in [PairDataSet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairDataSetSum, name, value)
    __swig_getmethods__ = {}
    for _s in [PairDataSet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PairDataSetSum, name)
    __repr__ = _swig_repr
    def dotProduct(self, *args): return _cpairdataset.PairDataSetSum_dotProduct(self, *args)
    def castToBase(self): return _cpairdataset.PairDataSetSum_castToBase(self)
    def duplicate(self, *args): return _cpairdataset.PairDataSetSum_duplicate(self, *args)
    def __init__(self, *args): 
        this = _cpairdataset.new_PairDataSetSum(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cpairdataset.delete_PairDataSetSum
    __del__ = lambda self : None;
PairDataSetSum_swigregister = _cpairdataset.PairDataSetSum_swigregister
PairDataSetSum_swigregister(PairDataSetSum)

class PairDataSetOrd(PairDataSet):
    __swig_setmethods__ = {}
    for _s in [PairDataSet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairDataSetOrd, name, value)
    __swig_getmethods__ = {}
    for _s in [PairDataSet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PairDataSetOrd, name)
    __repr__ = _swig_repr
    def dotProduct(self, *args): return _cpairdataset.PairDataSetOrd_dotProduct(self, *args)
    def castToBase(self): return _cpairdataset.PairDataSetOrd_castToBase(self)
    def duplicate(self, *args): return _cpairdataset.PairDataSetOrd_duplicate(self, *args)
    def __init__(self, *args): 
        this = _cpairdataset.new_PairDataSetOrd(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cpairdataset.delete_PairDataSetOrd
    __del__ = lambda self : None;
PairDataSetOrd_swigregister = _cpairdataset.PairDataSetOrd_swigregister
PairDataSetOrd_swigregister(PairDataSetOrd)



