# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_csetdata', [dirname(__file__)])
        except ImportError:
            import _csetdata
            return _csetdata
        if fp is not None:
            try:
                _mod = imp.load_module('_csetdata', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _csetdata = swig_import_helper()
    del swig_import_helper
else:
    import _csetdata
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _csetdata.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _csetdata.SwigPyIterator_value(self)
    def incr(self, n = 1): return _csetdata.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _csetdata.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _csetdata.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _csetdata.SwigPyIterator_equal(self, *args)
    def copy(self): return _csetdata.SwigPyIterator_copy(self)
    def next(self): return _csetdata.SwigPyIterator_next(self)
    def __next__(self): return _csetdata.SwigPyIterator___next__(self)
    def previous(self): return _csetdata.SwigPyIterator_previous(self)
    def advance(self, *args): return _csetdata.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _csetdata.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _csetdata.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _csetdata.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _csetdata.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _csetdata.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _csetdata.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _csetdata.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csetdata.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csetdata.IntVector___nonzero__(self)
    def __bool__(self): return _csetdata.IntVector___bool__(self)
    def __len__(self): return _csetdata.IntVector___len__(self)
    def pop(self): return _csetdata.IntVector_pop(self)
    def __getslice__(self, *args): return _csetdata.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csetdata.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csetdata.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csetdata.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csetdata.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csetdata.IntVector___setitem__(self, *args)
    def append(self, *args): return _csetdata.IntVector_append(self, *args)
    def empty(self): return _csetdata.IntVector_empty(self)
    def size(self): return _csetdata.IntVector_size(self)
    def clear(self): return _csetdata.IntVector_clear(self)
    def swap(self, *args): return _csetdata.IntVector_swap(self, *args)
    def get_allocator(self): return _csetdata.IntVector_get_allocator(self)
    def begin(self): return _csetdata.IntVector_begin(self)
    def end(self): return _csetdata.IntVector_end(self)
    def rbegin(self): return _csetdata.IntVector_rbegin(self)
    def rend(self): return _csetdata.IntVector_rend(self)
    def pop_back(self): return _csetdata.IntVector_pop_back(self)
    def erase(self, *args): return _csetdata.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csetdata.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csetdata.IntVector_push_back(self, *args)
    def front(self): return _csetdata.IntVector_front(self)
    def back(self): return _csetdata.IntVector_back(self)
    def assign(self, *args): return _csetdata.IntVector_assign(self, *args)
    def resize(self, *args): return _csetdata.IntVector_resize(self, *args)
    def insert(self, *args): return _csetdata.IntVector_insert(self, *args)
    def reserve(self, *args): return _csetdata.IntVector_reserve(self, *args)
    def capacity(self): return _csetdata.IntVector_capacity(self)
    __swig_destroy__ = _csetdata.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _csetdata.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csetdata.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csetdata.DoubleVector___nonzero__(self)
    def __bool__(self): return _csetdata.DoubleVector___bool__(self)
    def __len__(self): return _csetdata.DoubleVector___len__(self)
    def pop(self): return _csetdata.DoubleVector_pop(self)
    def __getslice__(self, *args): return _csetdata.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csetdata.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csetdata.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csetdata.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csetdata.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csetdata.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _csetdata.DoubleVector_append(self, *args)
    def empty(self): return _csetdata.DoubleVector_empty(self)
    def size(self): return _csetdata.DoubleVector_size(self)
    def clear(self): return _csetdata.DoubleVector_clear(self)
    def swap(self, *args): return _csetdata.DoubleVector_swap(self, *args)
    def get_allocator(self): return _csetdata.DoubleVector_get_allocator(self)
    def begin(self): return _csetdata.DoubleVector_begin(self)
    def end(self): return _csetdata.DoubleVector_end(self)
    def rbegin(self): return _csetdata.DoubleVector_rbegin(self)
    def rend(self): return _csetdata.DoubleVector_rend(self)
    def pop_back(self): return _csetdata.DoubleVector_pop_back(self)
    def erase(self, *args): return _csetdata.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csetdata.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csetdata.DoubleVector_push_back(self, *args)
    def front(self): return _csetdata.DoubleVector_front(self)
    def back(self): return _csetdata.DoubleVector_back(self)
    def assign(self, *args): return _csetdata.DoubleVector_assign(self, *args)
    def resize(self, *args): return _csetdata.DoubleVector_resize(self, *args)
    def insert(self, *args): return _csetdata.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _csetdata.DoubleVector_reserve(self, *args)
    def capacity(self): return _csetdata.DoubleVector_capacity(self)
    __swig_destroy__ = _csetdata.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _csetdata.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class DataSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DataSet, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["Y"] = _csetdata.DataSet_Y_set
    __swig_getmethods__["Y"] = _csetdata.DataSet_Y_get
    if _newclass:Y = _swig_property(_csetdata.DataSet_Y_get, _csetdata.DataSet_Y_set)
    __swig_setmethods__["norms"] = _csetdata.DataSet_norms_set
    __swig_getmethods__["norms"] = _csetdata.DataSet_norms_get
    if _newclass:norms = _swig_property(_csetdata.DataSet_norms_get, _csetdata.DataSet_norms_set)
    __swig_setmethods__["kernel"] = _csetdata.DataSet_kernel_set
    __swig_getmethods__["kernel"] = _csetdata.DataSet_kernel_get
    if _newclass:kernel = _swig_property(_csetdata.DataSet_kernel_get, _csetdata.DataSet_kernel_set)
    def setY(self, *args): return _csetdata.DataSet_setY(self, *args)
    def computeNorms(self): return _csetdata.DataSet_computeNorms(self)
    def setKernel(self, *args): return _csetdata.DataSet_setKernel(self, *args)
    def attachKernel(self, *args): return _csetdata.DataSet_attachKernel(self, *args)
    def getKernelMatrixAsVector(self): return _csetdata.DataSet_getKernelMatrixAsVector(self)
    def size(self): return _csetdata.DataSet_size(self)
    def dotProduct(self, *args): return _csetdata.DataSet_dotProduct(self, *args)
    def duplicate(self, *args): return _csetdata.DataSet_duplicate(self, *args)
    def castToBase(self): return _csetdata.DataSet_castToBase(self)
    def show(self): return _csetdata.DataSet_show(self)
    __swig_destroy__ = _csetdata.delete_DataSet
    __del__ = lambda self : None;
DataSet_swigregister = _csetdata.DataSet_swigregister
DataSet_swigregister(DataSet)

class SetData(DataSet):
    __swig_setmethods__ = {}
    for _s in [DataSet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SetData, name, value)
    __swig_getmethods__ = {}
    for _s in [DataSet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SetData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sets"] = _csetdata.SetData_sets_set
    __swig_getmethods__["sets"] = _csetdata.SetData_sets_get
    if _newclass:sets = _swig_property(_csetdata.SetData_sets_get, _csetdata.SetData_sets_set)
    __swig_setmethods__["data"] = _csetdata.SetData_data_set
    __swig_getmethods__["data"] = _csetdata.SetData_data_get
    if _newclass:data = _swig_property(_csetdata.SetData_data_get, _csetdata.SetData_data_set)
    def size(self): return _csetdata.SetData_size(self)
    def add(self, *args): return _csetdata.SetData_add(self, *args)
    def dotProduct(self, *args): return _csetdata.SetData_dotProduct(self, *args)
    def show(self): return _csetdata.SetData_show(self)
    def castToBase(self): return _csetdata.SetData_castToBase(self)
    def duplicate(self, *args): return _csetdata.SetData_duplicate(self, *args)
    def __init__(self, *args): 
        this = _csetdata.new_SetData(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _csetdata.delete_SetData
    __del__ = lambda self : None;
SetData_swigregister = _csetdata.SetData_swigregister
SetData_swigregister(SetData)



