# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_csparsedataset', [dirname(__file__)])
        except ImportError:
            import _csparsedataset
            return _csparsedataset
        if fp is not None:
            try:
                _mod = imp.load_module('_csparsedataset', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _csparsedataset = swig_import_helper()
    del swig_import_helper
else:
    import _csparsedataset
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _csparsedataset.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _csparsedataset.SwigPyIterator_value(self)
    def incr(self, n = 1): return _csparsedataset.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _csparsedataset.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _csparsedataset.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _csparsedataset.SwigPyIterator_equal(self, *args)
    def copy(self): return _csparsedataset.SwigPyIterator_copy(self)
    def next(self): return _csparsedataset.SwigPyIterator_next(self)
    def __next__(self): return _csparsedataset.SwigPyIterator___next__(self)
    def previous(self): return _csparsedataset.SwigPyIterator_previous(self)
    def advance(self, *args): return _csparsedataset.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _csparsedataset.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _csparsedataset.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _csparsedataset.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _csparsedataset.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _csparsedataset.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _csparsedataset.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _csparsedataset.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csparsedataset.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csparsedataset.IntVector___nonzero__(self)
    def __bool__(self): return _csparsedataset.IntVector___bool__(self)
    def __len__(self): return _csparsedataset.IntVector___len__(self)
    def pop(self): return _csparsedataset.IntVector_pop(self)
    def __getslice__(self, *args): return _csparsedataset.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csparsedataset.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csparsedataset.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csparsedataset.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csparsedataset.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csparsedataset.IntVector___setitem__(self, *args)
    def append(self, *args): return _csparsedataset.IntVector_append(self, *args)
    def empty(self): return _csparsedataset.IntVector_empty(self)
    def size(self): return _csparsedataset.IntVector_size(self)
    def clear(self): return _csparsedataset.IntVector_clear(self)
    def swap(self, *args): return _csparsedataset.IntVector_swap(self, *args)
    def get_allocator(self): return _csparsedataset.IntVector_get_allocator(self)
    def begin(self): return _csparsedataset.IntVector_begin(self)
    def end(self): return _csparsedataset.IntVector_end(self)
    def rbegin(self): return _csparsedataset.IntVector_rbegin(self)
    def rend(self): return _csparsedataset.IntVector_rend(self)
    def pop_back(self): return _csparsedataset.IntVector_pop_back(self)
    def erase(self, *args): return _csparsedataset.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csparsedataset.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csparsedataset.IntVector_push_back(self, *args)
    def front(self): return _csparsedataset.IntVector_front(self)
    def back(self): return _csparsedataset.IntVector_back(self)
    def assign(self, *args): return _csparsedataset.IntVector_assign(self, *args)
    def resize(self, *args): return _csparsedataset.IntVector_resize(self, *args)
    def insert(self, *args): return _csparsedataset.IntVector_insert(self, *args)
    def reserve(self, *args): return _csparsedataset.IntVector_reserve(self, *args)
    def capacity(self): return _csparsedataset.IntVector_capacity(self)
    __swig_destroy__ = _csparsedataset.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _csparsedataset.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csparsedataset.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csparsedataset.DoubleVector___nonzero__(self)
    def __bool__(self): return _csparsedataset.DoubleVector___bool__(self)
    def __len__(self): return _csparsedataset.DoubleVector___len__(self)
    def pop(self): return _csparsedataset.DoubleVector_pop(self)
    def __getslice__(self, *args): return _csparsedataset.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csparsedataset.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csparsedataset.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csparsedataset.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csparsedataset.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csparsedataset.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _csparsedataset.DoubleVector_append(self, *args)
    def empty(self): return _csparsedataset.DoubleVector_empty(self)
    def size(self): return _csparsedataset.DoubleVector_size(self)
    def clear(self): return _csparsedataset.DoubleVector_clear(self)
    def swap(self, *args): return _csparsedataset.DoubleVector_swap(self, *args)
    def get_allocator(self): return _csparsedataset.DoubleVector_get_allocator(self)
    def begin(self): return _csparsedataset.DoubleVector_begin(self)
    def end(self): return _csparsedataset.DoubleVector_end(self)
    def rbegin(self): return _csparsedataset.DoubleVector_rbegin(self)
    def rend(self): return _csparsedataset.DoubleVector_rend(self)
    def pop_back(self): return _csparsedataset.DoubleVector_pop_back(self)
    def erase(self, *args): return _csparsedataset.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csparsedataset.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csparsedataset.DoubleVector_push_back(self, *args)
    def front(self): return _csparsedataset.DoubleVector_front(self)
    def back(self): return _csparsedataset.DoubleVector_back(self)
    def assign(self, *args): return _csparsedataset.DoubleVector_assign(self, *args)
    def resize(self, *args): return _csparsedataset.DoubleVector_resize(self, *args)
    def insert(self, *args): return _csparsedataset.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _csparsedataset.DoubleVector_reserve(self, *args)
    def capacity(self): return _csparsedataset.DoubleVector_capacity(self)
    __swig_destroy__ = _csparsedataset.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _csparsedataset.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csparsedataset.FloatVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csparsedataset.FloatVector___nonzero__(self)
    def __bool__(self): return _csparsedataset.FloatVector___bool__(self)
    def __len__(self): return _csparsedataset.FloatVector___len__(self)
    def pop(self): return _csparsedataset.FloatVector_pop(self)
    def __getslice__(self, *args): return _csparsedataset.FloatVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csparsedataset.FloatVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csparsedataset.FloatVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csparsedataset.FloatVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csparsedataset.FloatVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csparsedataset.FloatVector___setitem__(self, *args)
    def append(self, *args): return _csparsedataset.FloatVector_append(self, *args)
    def empty(self): return _csparsedataset.FloatVector_empty(self)
    def size(self): return _csparsedataset.FloatVector_size(self)
    def clear(self): return _csparsedataset.FloatVector_clear(self)
    def swap(self, *args): return _csparsedataset.FloatVector_swap(self, *args)
    def get_allocator(self): return _csparsedataset.FloatVector_get_allocator(self)
    def begin(self): return _csparsedataset.FloatVector_begin(self)
    def end(self): return _csparsedataset.FloatVector_end(self)
    def rbegin(self): return _csparsedataset.FloatVector_rbegin(self)
    def rend(self): return _csparsedataset.FloatVector_rend(self)
    def pop_back(self): return _csparsedataset.FloatVector_pop_back(self)
    def erase(self, *args): return _csparsedataset.FloatVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csparsedataset.new_FloatVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csparsedataset.FloatVector_push_back(self, *args)
    def front(self): return _csparsedataset.FloatVector_front(self)
    def back(self): return _csparsedataset.FloatVector_back(self)
    def assign(self, *args): return _csparsedataset.FloatVector_assign(self, *args)
    def resize(self, *args): return _csparsedataset.FloatVector_resize(self, *args)
    def insert(self, *args): return _csparsedataset.FloatVector_insert(self, *args)
    def reserve(self, *args): return _csparsedataset.FloatVector_reserve(self, *args)
    def capacity(self): return _csparsedataset.FloatVector_capacity(self)
    __swig_destroy__ = _csparsedataset.delete_FloatVector
    __del__ = lambda self : None;
FloatVector_swigregister = _csparsedataset.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csparsedataset.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csparsedataset.StringVector___nonzero__(self)
    def __bool__(self): return _csparsedataset.StringVector___bool__(self)
    def __len__(self): return _csparsedataset.StringVector___len__(self)
    def pop(self): return _csparsedataset.StringVector_pop(self)
    def __getslice__(self, *args): return _csparsedataset.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csparsedataset.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csparsedataset.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csparsedataset.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csparsedataset.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csparsedataset.StringVector___setitem__(self, *args)
    def append(self, *args): return _csparsedataset.StringVector_append(self, *args)
    def empty(self): return _csparsedataset.StringVector_empty(self)
    def size(self): return _csparsedataset.StringVector_size(self)
    def clear(self): return _csparsedataset.StringVector_clear(self)
    def swap(self, *args): return _csparsedataset.StringVector_swap(self, *args)
    def get_allocator(self): return _csparsedataset.StringVector_get_allocator(self)
    def begin(self): return _csparsedataset.StringVector_begin(self)
    def end(self): return _csparsedataset.StringVector_end(self)
    def rbegin(self): return _csparsedataset.StringVector_rbegin(self)
    def rend(self): return _csparsedataset.StringVector_rend(self)
    def pop_back(self): return _csparsedataset.StringVector_pop_back(self)
    def erase(self, *args): return _csparsedataset.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csparsedataset.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csparsedataset.StringVector_push_back(self, *args)
    def front(self): return _csparsedataset.StringVector_front(self)
    def back(self): return _csparsedataset.StringVector_back(self)
    def assign(self, *args): return _csparsedataset.StringVector_assign(self, *args)
    def resize(self, *args): return _csparsedataset.StringVector_resize(self, *args)
    def insert(self, *args): return _csparsedataset.StringVector_insert(self, *args)
    def reserve(self, *args): return _csparsedataset.StringVector_reserve(self, *args)
    def capacity(self): return _csparsedataset.StringVector_capacity(self)
    __swig_destroy__ = _csparsedataset.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _csparsedataset.StringVector_swigregister
StringVector_swigregister(StringVector)

class LongVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LongVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LongVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csparsedataset.LongVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csparsedataset.LongVector___nonzero__(self)
    def __bool__(self): return _csparsedataset.LongVector___bool__(self)
    def __len__(self): return _csparsedataset.LongVector___len__(self)
    def pop(self): return _csparsedataset.LongVector_pop(self)
    def __getslice__(self, *args): return _csparsedataset.LongVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csparsedataset.LongVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csparsedataset.LongVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csparsedataset.LongVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csparsedataset.LongVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csparsedataset.LongVector___setitem__(self, *args)
    def append(self, *args): return _csparsedataset.LongVector_append(self, *args)
    def empty(self): return _csparsedataset.LongVector_empty(self)
    def size(self): return _csparsedataset.LongVector_size(self)
    def clear(self): return _csparsedataset.LongVector_clear(self)
    def swap(self, *args): return _csparsedataset.LongVector_swap(self, *args)
    def get_allocator(self): return _csparsedataset.LongVector_get_allocator(self)
    def begin(self): return _csparsedataset.LongVector_begin(self)
    def end(self): return _csparsedataset.LongVector_end(self)
    def rbegin(self): return _csparsedataset.LongVector_rbegin(self)
    def rend(self): return _csparsedataset.LongVector_rend(self)
    def pop_back(self): return _csparsedataset.LongVector_pop_back(self)
    def erase(self, *args): return _csparsedataset.LongVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csparsedataset.new_LongVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csparsedataset.LongVector_push_back(self, *args)
    def front(self): return _csparsedataset.LongVector_front(self)
    def back(self): return _csparsedataset.LongVector_back(self)
    def assign(self, *args): return _csparsedataset.LongVector_assign(self, *args)
    def resize(self, *args): return _csparsedataset.LongVector_resize(self, *args)
    def insert(self, *args): return _csparsedataset.LongVector_insert(self, *args)
    def reserve(self, *args): return _csparsedataset.LongVector_reserve(self, *args)
    def capacity(self): return _csparsedataset.LongVector_capacity(self)
    __swig_destroy__ = _csparsedataset.delete_LongVector
    __del__ = lambda self : None;
LongVector_swigregister = _csparsedataset.LongVector_swigregister
LongVector_swigregister(LongVector)

class DataSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DataSet, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["Y"] = _csparsedataset.DataSet_Y_set
    __swig_getmethods__["Y"] = _csparsedataset.DataSet_Y_get
    if _newclass:Y = _swig_property(_csparsedataset.DataSet_Y_get, _csparsedataset.DataSet_Y_set)
    __swig_setmethods__["norms"] = _csparsedataset.DataSet_norms_set
    __swig_getmethods__["norms"] = _csparsedataset.DataSet_norms_get
    if _newclass:norms = _swig_property(_csparsedataset.DataSet_norms_get, _csparsedataset.DataSet_norms_set)
    __swig_setmethods__["kernel"] = _csparsedataset.DataSet_kernel_set
    __swig_getmethods__["kernel"] = _csparsedataset.DataSet_kernel_get
    if _newclass:kernel = _swig_property(_csparsedataset.DataSet_kernel_get, _csparsedataset.DataSet_kernel_set)
    def setY(self, *args): return _csparsedataset.DataSet_setY(self, *args)
    def computeNorms(self): return _csparsedataset.DataSet_computeNorms(self)
    def setKernel(self, *args): return _csparsedataset.DataSet_setKernel(self, *args)
    def attachKernel(self, *args): return _csparsedataset.DataSet_attachKernel(self, *args)
    def getKernelMatrixAsVector(self): return _csparsedataset.DataSet_getKernelMatrixAsVector(self)
    def size(self): return _csparsedataset.DataSet_size(self)
    def dotProduct(self, *args): return _csparsedataset.DataSet_dotProduct(self, *args)
    def duplicate(self, *args): return _csparsedataset.DataSet_duplicate(self, *args)
    def castToBase(self): return _csparsedataset.DataSet_castToBase(self)
    def show(self): return _csparsedataset.DataSet_show(self)
    __swig_destroy__ = _csparsedataset.delete_DataSet
    __del__ = lambda self : None;
DataSet_swigregister = _csparsedataset.DataSet_swigregister
DataSet_swigregister(DataSet)

class SparseDataSet(DataSet):
    __swig_setmethods__ = {}
    for _s in [DataSet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SparseDataSet, name, value)
    __swig_getmethods__ = {}
    for _s in [DataSet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SparseDataSet, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n"] = _csparsedataset.SparseDataSet_n_set
    __swig_getmethods__["n"] = _csparsedataset.SparseDataSet_n_get
    if _newclass:n = _swig_property(_csparsedataset.SparseDataSet_n_get, _csparsedataset.SparseDataSet_n_set)
    __swig_setmethods__["numFeatures"] = _csparsedataset.SparseDataSet_numFeatures_set
    __swig_getmethods__["numFeatures"] = _csparsedataset.SparseDataSet_numFeatures_get
    if _newclass:numFeatures = _swig_property(_csparsedataset.SparseDataSet_numFeatures_get, _csparsedataset.SparseDataSet_numFeatures_set)
    __swig_setmethods__["prob"] = _csparsedataset.SparseDataSet_prob_set
    __swig_getmethods__["prob"] = _csparsedataset.SparseDataSet_prob_get
    if _newclass:prob = _swig_property(_csparsedataset.SparseDataSet_prob_get, _csparsedataset.SparseDataSet_prob_set)
    __swig_setmethods__["featureIDmap"] = _csparsedataset.SparseDataSet_featureIDmap_set
    __swig_getmethods__["featureIDmap"] = _csparsedataset.SparseDataSet_featureIDmap_get
    if _newclass:featureIDmap = _swig_property(_csparsedataset.SparseDataSet_featureIDmap_get, _csparsedataset.SparseDataSet_featureIDmap_set)
    __swig_setmethods__["X"] = _csparsedataset.SparseDataSet_X_set
    __swig_getmethods__["X"] = _csparsedataset.SparseDataSet_X_get
    if _newclass:X = _swig_property(_csparsedataset.SparseDataSet_X_get, _csparsedataset.SparseDataSet_X_set)
    __swig_setmethods__["featureName"] = _csparsedataset.SparseDataSet_featureName_set
    __swig_getmethods__["featureName"] = _csparsedataset.SparseDataSet_featureName_get
    if _newclass:featureName = _swig_property(_csparsedataset.SparseDataSet_featureName_get, _csparsedataset.SparseDataSet_featureName_set)
    def __init__(self, *args): 
        this = _csparsedataset.new_SparseDataSet(*args)
        try: self.this.append(this)
        except: self.this = this
    def size(self): return _csparsedataset.SparseDataSet_size(self)
    def castToBase(self): return _csparsedataset.SparseDataSet_castToBase(self)
    def getPattern(self, *args): return _csparsedataset.SparseDataSet_getPattern(self, *args)
    def getPatternValues(self, *args): return _csparsedataset.SparseDataSet_getPatternValues(self, *args)
    def getPatternKeys(self, *args): return _csparsedataset.SparseDataSet_getPatternKeys(self, *args)
    def getPatternSparse(self, *args): return _csparsedataset.SparseDataSet_getPatternSparse(self, *args)
    def getFeature(self, *args): return _csparsedataset.SparseDataSet_getFeature(self, *args)
    def show(self): return _csparsedataset.SparseDataSet_show(self)
    def duplicate(self, *args): return _csparsedataset.SparseDataSet_duplicate(self, *args)
    __swig_destroy__ = _csparsedataset.delete_SparseDataSet
    __del__ = lambda self : None;
    def addPattern(self, *args): return _csparsedataset.SparseDataSet_addPattern(self, *args)
    def addFeature(self, *args): return _csparsedataset.SparseDataSet_addFeature(self, *args)
    def addFeatures(self, *args): return _csparsedataset.SparseDataSet_addFeatures(self, *args)
    def featureIDcompute(self): return _csparsedataset.SparseDataSet_featureIDcompute(self)
    def setFeatureName(self, *args): return _csparsedataset.SparseDataSet_setFeatureName(self, *args)
    def getFeatureID(self, *args): return _csparsedataset.SparseDataSet_getFeatureID(self, *args)
    def eliminateFeatures(self, *args): return _csparsedataset.SparseDataSet_eliminateFeatures(self, *args)
    def normalize(self, *args): return _csparsedataset.SparseDataSet_normalize(self, *args)
    def scale(self, *args): return _csparsedataset.SparseDataSet_scale(self, *args)
    def translate(self, *args): return _csparsedataset.SparseDataSet_translate(self, *args)
    def mean(self, *args): return _csparsedataset.SparseDataSet_mean(self, *args)
    def standardDeviation(self, *args): return _csparsedataset.SparseDataSet_standardDeviation(self, *args)
    def weightedSum(self, *args): return _csparsedataset.SparseDataSet_weightedSum(self, *args)
    def commonFeatures(self, *args): return _csparsedataset.SparseDataSet_commonFeatures(self, *args)
    def featureCount(self, *args): return _csparsedataset.SparseDataSet_featureCount(self, *args)
    def featureCounts(self, *args): return _csparsedataset.SparseDataSet_featureCounts(self, *args)
    def nonzero(self, *args): return _csparsedataset.SparseDataSet_nonzero(self, *args)
    def dotProduct(self, *args): return _csparsedataset.SparseDataSet_dotProduct(self, *args)
    def libsvm_construct(self, *args): return _csparsedataset.SparseDataSet_libsvm_construct(self, *args)
SparseDataSet_swigregister = _csparsedataset.SparseDataSet_swigregister
SparseDataSet_swigregister(SparseDataSet)



