# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_csparsefeaturevector', [dirname(__file__)])
        except ImportError:
            import _csparsefeaturevector
            return _csparsefeaturevector
        if fp is not None:
            try:
                _mod = imp.load_module('_csparsefeaturevector', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _csparsefeaturevector = swig_import_helper()
    del swig_import_helper
else:
    import _csparsefeaturevector
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Feature(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Feature, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Feature, name)
    __repr__ = _swig_repr
    __swig_setmethods__["index"] = _csparsefeaturevector.Feature_index_set
    __swig_getmethods__["index"] = _csparsefeaturevector.Feature_index_get
    if _newclass:index = _swig_property(_csparsefeaturevector.Feature_index_get, _csparsefeaturevector.Feature_index_set)
    __swig_setmethods__["value"] = _csparsefeaturevector.Feature_value_set
    __swig_getmethods__["value"] = _csparsefeaturevector.Feature_value_get
    if _newclass:value = _swig_property(_csparsefeaturevector.Feature_value_get, _csparsefeaturevector.Feature_value_set)
    def __init__(self, *args): 
        this = _csparsefeaturevector.new_Feature(*args)
        try: self.this.append(this)
        except: self.this = this
    def compare(self, *args): return _csparsefeaturevector.Feature_compare(self, *args)
    __swig_destroy__ = _csparsefeaturevector.delete_Feature
    __del__ = lambda self : None;
Feature_swigregister = _csparsefeaturevector.Feature_swigregister
Feature_swigregister(Feature)

class SparseFeatureVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SparseFeatureVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SparseFeatureVector, name)
    __repr__ = _swig_repr
    __swig_setmethods__["features"] = _csparsefeaturevector.SparseFeatureVector_features_set
    __swig_getmethods__["features"] = _csparsefeaturevector.SparseFeatureVector_features_get
    if _newclass:features = _swig_property(_csparsefeaturevector.SparseFeatureVector_features_get, _csparsefeaturevector.SparseFeatureVector_features_set)
    def __init__(self, *args): 
        this = _csparsefeaturevector.new_SparseFeatureVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def initialize(self, *args): return _csparsefeaturevector.SparseFeatureVector_initialize(self, *args)
    def get(self, *args): return _csparsefeaturevector.SparseFeatureVector_get(self, *args)
    def getValues(self): return _csparsefeaturevector.SparseFeatureVector_getValues(self)
    def getKeys(self): return _csparsefeaturevector.SparseFeatureVector_getKeys(self)
    def add(self, *args): return _csparsefeaturevector.SparseFeatureVector_add(self, *args)
    def printData(self): return _csparsefeaturevector.SparseFeatureVector_printData(self)
    def commonFeatures(self, *args): return _csparsefeaturevector.SparseFeatureVector_commonFeatures(self, *args)
    def scale(self, *args): return _csparsefeaturevector.SparseFeatureVector_scale(self, *args)
    def norm(self, *args): return _csparsefeaturevector.SparseFeatureVector_norm(self, *args)
    def dotProduct(self, *args): return _csparsefeaturevector.SparseFeatureVector_dotProduct(self, *args)
    def size(self): return _csparsefeaturevector.SparseFeatureVector_size(self)
    __swig_destroy__ = _csparsefeaturevector.delete_SparseFeatureVector
    __del__ = lambda self : None;
SparseFeatureVector_swigregister = _csparsefeaturevector.SparseFeatureVector_swigregister
SparseFeatureVector_swigregister(SparseFeatureVector)



