# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_csvmodel', [dirname(__file__)])
        except ImportError:
            import _csvmodel
            return _csvmodel
        if fp is not None:
            try:
                _mod = imp.load_module('_csvmodel', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _csvmodel = swig_import_helper()
    del swig_import_helper
else:
    import _csvmodel
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _csvmodel.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _csvmodel.SwigPyIterator_value(self)
    def incr(self, n = 1): return _csvmodel.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _csvmodel.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _csvmodel.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _csvmodel.SwigPyIterator_equal(self, *args)
    def copy(self): return _csvmodel.SwigPyIterator_copy(self)
    def next(self): return _csvmodel.SwigPyIterator_next(self)
    def __next__(self): return _csvmodel.SwigPyIterator___next__(self)
    def previous(self): return _csvmodel.SwigPyIterator_previous(self)
    def advance(self, *args): return _csvmodel.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _csvmodel.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _csvmodel.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _csvmodel.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _csvmodel.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _csvmodel.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _csvmodel.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _csvmodel.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csvmodel.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csvmodel.IntVector___nonzero__(self)
    def __bool__(self): return _csvmodel.IntVector___bool__(self)
    def __len__(self): return _csvmodel.IntVector___len__(self)
    def pop(self): return _csvmodel.IntVector_pop(self)
    def __getslice__(self, *args): return _csvmodel.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csvmodel.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csvmodel.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csvmodel.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csvmodel.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csvmodel.IntVector___setitem__(self, *args)
    def append(self, *args): return _csvmodel.IntVector_append(self, *args)
    def empty(self): return _csvmodel.IntVector_empty(self)
    def size(self): return _csvmodel.IntVector_size(self)
    def clear(self): return _csvmodel.IntVector_clear(self)
    def swap(self, *args): return _csvmodel.IntVector_swap(self, *args)
    def get_allocator(self): return _csvmodel.IntVector_get_allocator(self)
    def begin(self): return _csvmodel.IntVector_begin(self)
    def end(self): return _csvmodel.IntVector_end(self)
    def rbegin(self): return _csvmodel.IntVector_rbegin(self)
    def rend(self): return _csvmodel.IntVector_rend(self)
    def pop_back(self): return _csvmodel.IntVector_pop_back(self)
    def erase(self, *args): return _csvmodel.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csvmodel.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csvmodel.IntVector_push_back(self, *args)
    def front(self): return _csvmodel.IntVector_front(self)
    def back(self): return _csvmodel.IntVector_back(self)
    def assign(self, *args): return _csvmodel.IntVector_assign(self, *args)
    def resize(self, *args): return _csvmodel.IntVector_resize(self, *args)
    def insert(self, *args): return _csvmodel.IntVector_insert(self, *args)
    def reserve(self, *args): return _csvmodel.IntVector_reserve(self, *args)
    def capacity(self): return _csvmodel.IntVector_capacity(self)
    __swig_destroy__ = _csvmodel.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _csvmodel.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _csvmodel.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _csvmodel.DoubleVector___nonzero__(self)
    def __bool__(self): return _csvmodel.DoubleVector___bool__(self)
    def __len__(self): return _csvmodel.DoubleVector___len__(self)
    def pop(self): return _csvmodel.DoubleVector_pop(self)
    def __getslice__(self, *args): return _csvmodel.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _csvmodel.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _csvmodel.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _csvmodel.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _csvmodel.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _csvmodel.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _csvmodel.DoubleVector_append(self, *args)
    def empty(self): return _csvmodel.DoubleVector_empty(self)
    def size(self): return _csvmodel.DoubleVector_size(self)
    def clear(self): return _csvmodel.DoubleVector_clear(self)
    def swap(self, *args): return _csvmodel.DoubleVector_swap(self, *args)
    def get_allocator(self): return _csvmodel.DoubleVector_get_allocator(self)
    def begin(self): return _csvmodel.DoubleVector_begin(self)
    def end(self): return _csvmodel.DoubleVector_end(self)
    def rbegin(self): return _csvmodel.DoubleVector_rbegin(self)
    def rend(self): return _csvmodel.DoubleVector_rend(self)
    def pop_back(self): return _csvmodel.DoubleVector_pop_back(self)
    def erase(self, *args): return _csvmodel.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _csvmodel.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _csvmodel.DoubleVector_push_back(self, *args)
    def front(self): return _csvmodel.DoubleVector_front(self)
    def back(self): return _csvmodel.DoubleVector_back(self)
    def assign(self, *args): return _csvmodel.DoubleVector_assign(self, *args)
    def resize(self, *args): return _csvmodel.DoubleVector_resize(self, *args)
    def insert(self, *args): return _csvmodel.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _csvmodel.DoubleVector_reserve(self, *args)
    def capacity(self): return _csvmodel.DoubleVector_capacity(self)
    __swig_destroy__ = _csvmodel.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _csvmodel.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class SVModel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SVModel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SVModel, name)
    __repr__ = _swig_repr
    __swig_setmethods__["svdata"] = _csvmodel.SVModel_svdata_set
    __swig_getmethods__["svdata"] = _csvmodel.SVModel_svdata_get
    if _newclass:svdata = _swig_property(_csvmodel.SVModel_svdata_get, _csvmodel.SVModel_svdata_set)
    __swig_setmethods__["alpha"] = _csvmodel.SVModel_alpha_set
    __swig_getmethods__["alpha"] = _csvmodel.SVModel_alpha_get
    if _newclass:alpha = _swig_property(_csvmodel.SVModel_alpha_get, _csvmodel.SVModel_alpha_set)
    __swig_setmethods__["b"] = _csvmodel.SVModel_b_set
    __swig_getmethods__["b"] = _csvmodel.SVModel_b_get
    if _newclass:b = _swig_property(_csvmodel.SVModel_b_get, _csvmodel.SVModel_b_set)
    __swig_setmethods__["numSV"] = _csvmodel.SVModel_numSV_set
    __swig_getmethods__["numSV"] = _csvmodel.SVModel_numSV_get
    if _newclass:numSV = _swig_property(_csvmodel.SVModel_numSV_get, _csvmodel.SVModel_numSV_set)
    def decisionFunc(self, *args): return _csvmodel.SVModel_decisionFunc(self, *args)
    def __init__(self, *args): 
        this = _csvmodel.new_SVModel(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _csvmodel.delete_SVModel
    __del__ = lambda self : None;
SVModel_swigregister = _csvmodel.SVModel_swigregister
SVModel_swigregister(SVModel)

class LinearSVModel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearSVModel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearSVModel, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _csvmodel.new_LinearSVModel(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _csvmodel.delete_LinearSVModel
    __del__ = lambda self : None;
    __swig_setmethods__["w"] = _csvmodel.LinearSVModel_w_set
    __swig_getmethods__["w"] = _csvmodel.LinearSVModel_w_get
    if _newclass:w = _swig_property(_csvmodel.LinearSVModel_w_get, _csvmodel.LinearSVModel_w_set)
    __swig_setmethods__["wVec"] = _csvmodel.LinearSVModel_wVec_set
    __swig_getmethods__["wVec"] = _csvmodel.LinearSVModel_wVec_get
    if _newclass:wVec = _swig_property(_csvmodel.LinearSVModel_wVec_get, _csvmodel.LinearSVModel_wVec_set)
    __swig_setmethods__["b"] = _csvmodel.LinearSVModel_b_set
    __swig_getmethods__["b"] = _csvmodel.LinearSVModel_b_get
    if _newclass:b = _swig_property(_csvmodel.LinearSVModel_b_get, _csvmodel.LinearSVModel_b_set)
    def getW(self, *args): return _csvmodel.LinearSVModel_getW(self, *args)
    def getWvec(self): return _csvmodel.LinearSVModel_getWvec(self)
    def decisionFunc(self, *args): return _csvmodel.LinearSVModel_decisionFunc(self, *args)
LinearSVModel_swigregister = _csvmodel.LinearSVModel_swigregister
LinearSVModel_swigregister(LinearSVModel)

class LinearSparseSVModel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearSparseSVModel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearSparseSVModel, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _csvmodel.new_LinearSparseSVModel(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _csvmodel.delete_LinearSparseSVModel
    __del__ = lambda self : None;
    __swig_setmethods__["w"] = _csvmodel.LinearSparseSVModel_w_set
    __swig_getmethods__["w"] = _csvmodel.LinearSparseSVModel_w_get
    if _newclass:w = _swig_property(_csvmodel.LinearSparseSVModel_w_get, _csvmodel.LinearSparseSVModel_w_set)
    __swig_setmethods__["wVec"] = _csvmodel.LinearSparseSVModel_wVec_set
    __swig_getmethods__["wVec"] = _csvmodel.LinearSparseSVModel_wVec_get
    if _newclass:wVec = _swig_property(_csvmodel.LinearSparseSVModel_wVec_get, _csvmodel.LinearSparseSVModel_wVec_set)
    __swig_setmethods__["b"] = _csvmodel.LinearSparseSVModel_b_set
    __swig_getmethods__["b"] = _csvmodel.LinearSparseSVModel_b_get
    if _newclass:b = _swig_property(_csvmodel.LinearSparseSVModel_b_get, _csvmodel.LinearSparseSVModel_b_set)
    def getW(self, *args): return _csvmodel.LinearSparseSVModel_getW(self, *args)
    def getWvec(self): return _csvmodel.LinearSparseSVModel_getWvec(self)
    def decisionFunc(self, *args): return _csvmodel.LinearSparseSVModel_decisionFunc(self, *args)
LinearSparseSVModel_swigregister = _csvmodel.LinearSparseSVModel_swigregister
LinearSparseSVModel_swigregister(LinearSparseSVModel)



